### ISSUE TITLE
Splitting Videos in the Timeline doesn't work

### ISSUE THREAD

**Issue by Zavecen** [James231/Unity-Video-Editor-Template#2]
I tried splitting a video file on the timeline but all it did was produce one unplayable segment and one segment which starts from the beginning.

**Comment by James231** [comment]
Thanks for raising the issue.

As a work around you can create two video tracks which play the same clip and set the start and end times. For example track 1 can start 0 seconds into the video, and end at 10 seconds, and track 2 can start 20 seconds into the video and end at 30 seconds.

This issue is fixable and [this is the file causing it](https://github.com/James231/Unity-Video-Editor-Template/blob/master/Assets/VideoEditorAssets/ModifiedDefaultPlayables/Video/VideoPlayableBehaviour.cs).

**Comment by Zavecen** [comment]
![Annotation 2020-06-28 162713](https://user-images.githubusercontent.com/55150712/85952558-07fa5000-b962-11ea-9fef-0d281dc2fe2f.png)
So when adjusting these values it seems to only shift the segment forward or back in the timeline, I can't seem to change the start point of the video.

**Comment by James231** [comment]
Yes, the 'Clip Timing' values change the position of the video clip in timeline.
To change the start and end points of the video, use the 'Start Time' and 'End Time' values:

![image](https://user-images.githubusercontent.com/27020398/85953032-7096fc00-b965-11ea-9ebe-21de767087b7.png)

In this screenshot, when the video starts playing it will play for 10 seconds, starting 10 seconds into the video clip and finishing 20 seconds into the clip.

You can set the end time to -1 if you want it to continue until the end of the clip without having to specify the extact time

**Comment by Zavecen** [comment]
Ah ok thats explains a lot, ill do that.
